name: Check Proxy

on:
  schedule:
    - cron: "0 * * * *"  # setiap jam
  workflow_dispatch:

jobs:
  check-proxy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run proxy checker
        run: python scripts/check_proxy.py

      - name: Commit results
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add -f result/active.txt result/dead.txt
          git commit -m "update result" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
