name: Proxy Checker
on:
  schedule:
    - cron: '0 17 * * *'  
  workflow_dispatch:

jobs:
  proxy-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: pip install requests beautifulsoup4
      
    - name: Run Proxy Checker
      run: python proxy_checker.py
      
    - name: Commit results
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add rawProxy.txt active.txt dead.txt
        git commit -m "Update proxy lists [skip ci]" || echo "No changes to commit"
        git push
